SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE VIEW [dbo].[V#UGFGA]
AS
SELECT     FGA_CODE, ORGN_OGID, SYS_USER
FROM         dbo.User_Organ_Fgac
WHERE     (REC_STAT = '002') AND (VALD_TYPE = '002')


GO
