SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[V#URFGA]
AS
SELECT     FGA_CODE, REGN_PRVN_CODE, REGN_CODE, SYS_USER
FROM         dbo.User_Region_Fgac
WHERE     (REC_STAT = '002') AND (VALD_TYPE = '002')

GO
