CREATE TABLE [dbo].[Service_Robot_Visit]
(
[SRRB_SERV_FILE_NO] [bigint] NULL,
[SRRB_ROBO_RBID] [bigint] NULL,
[SRID] [bigint] NOT NULL IDENTITY(1, 1),
[VIST_DATE] [datetime] NULL CONSTRAINT [DF__Service_R__VIST___68487DD7] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Service_Robot_Visit] ADD CONSTRAINT [PK_SRVS] PRIMARY KEY CLUSTERED  ([SRID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Service_Robot_Visit] ADD CONSTRAINT [FK__Service_Robot_Vi__693CA210] FOREIGN KEY ([SRRB_SERV_FILE_NO], [SRRB_ROBO_RBID]) REFERENCES [dbo].[Service_Robot] ([SERV_FILE_NO], [ROBO_RBID]) ON DELETE CASCADE
GO
