CREATE TABLE [dbo].[Admin]
(
[ORGN_OGID] [bigint] NOT NULL,
[SERV_FILE_NO] [bigint] NOT NULL,
[STAT] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Admin] ADD CONSTRAINT [PK_Admin] PRIMARY KEY CLUSTERED  ([ORGN_OGID], [SERV_FILE_NO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Admin] WITH NOCHECK ADD CONSTRAINT [FK_Admin_Organ] FOREIGN KEY ([ORGN_OGID]) REFERENCES [dbo].[Organ] ([OGID])
GO
ALTER TABLE [dbo].[Admin] WITH NOCHECK ADD CONSTRAINT [FK_Admin_Service] FOREIGN KEY ([SERV_FILE_NO]) REFERENCES [dbo].[Service] ([FILE_NO])
GO
