CREATE TABLE [dbo].[Robot_Spy_Group]
(
[ROBO_RBID] [bigint] NOT NULL,
[GROP_CODE] [bigint] NOT NULL,
[GROP_NAME] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Robot_Spy_Group] ADD CONSTRAINT [PK_Robot_Spy_Group] PRIMARY KEY CLUSTERED  ([ROBO_RBID], [GROP_CODE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Robot_Spy_Group] ADD CONSTRAINT [FK_RSPG_ROBO] FOREIGN KEY ([ROBO_RBID]) REFERENCES [dbo].[Robot] ([RBID])
GO
