CREATE TABLE [dbo].[Service]
(
[FILE_NO] [bigint] NOT NULL CONSTRAINT [DF_Service_FILE_NO] DEFAULT ([dbo].[GNRT_NVID_U]()),
[CELL_PHON] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FRST_NAME] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_NAME] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_NAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHAT_ID] [bigint] NULL,
[STAT] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_Service_STAT] DEFAULT ('002'),
[VRFY_CODE] [int] NULL,
[IMAG_PROF] [image] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Service] ADD CONSTRAINT [PK_SERV] PRIMARY KEY CLUSTERED  ([FILE_NO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Service_FILE_NO] ON [dbo].[Service] ([FILE_NO]) ON [PRIMARY]
GO
